import { Recipe, Store, MealPlan, GroceryComparison, ChatMessage, UserProfile, RecipeJournalEntry, ShortFormContent } from "@/types";

export const dummyStores: Store[] = [
  {
    id: "tj",
    name: "Trader Joe's",
    address: "855 El Camino Real, Palo Alto, CA",
    distance: 0.8,
    distanceUnit: "mi",
  },
  {
    id: "wf",
    name: "Whole Foods",
    address: "774 Emerson St, Palo Alto, CA",
    distance: 1.2,
    distanceUnit: "mi",
  },
  {
    id: "safeway",
    name: "Safeway",
    address: "325 S California Ave, Palo Alto, CA",
    distance: 1.5,
    distanceUnit: "mi",
  },
];

export const dummyRecipes: Recipe[] = [
  {
    id: "1",
    name: "Creamy Lentil Dal",
    description: "A comforting, protein-rich Indian classic that's perfect for beginners. Warm spices and creamy coconut make this dish irresistible.",
    ingredients: [
      { name: "Red lentils", amount: 1, unit: "cup", price: 2.99, cheapestStore: "Trader Joe's", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 2.99, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 4.49, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 3.79, inStock: true },
      ]},
      { name: "Coconut milk", amount: 1, unit: "can", price: 1.99, cheapestStore: "Trader Joe's", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 1.99, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 2.99, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 2.49, inStock: false },
      ]},
      { name: "Onion", amount: 1, unit: "medium", price: 0.50, cheapestStore: "Safeway" },
      { name: "Garlic", amount: 3, unit: "cloves", price: 0.30, cheapestStore: "Trader Joe's" },
      { name: "Ginger", amount: 1, unit: "inch", price: 0.25, cheapestStore: "Trader Joe's" },
      { name: "Turmeric", amount: 1, unit: "tsp", price: 0.15, cheapestStore: "Trader Joe's" },
      { name: "Cumin", amount: 1, unit: "tsp", price: 0.15, cheapestStore: "Trader Joe's" },
      { name: "Garam masala", amount: 1, unit: "tsp", price: 0.20, cheapestStore: "Trader Joe's" },
      { name: "Vegetable broth", amount: 2, unit: "cups", price: 1.50, cheapestStore: "Trader Joe's" },
      { name: "Spinach", amount: 2, unit: "cups", price: 2.29, cheapestStore: "Safeway", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 2.49, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 3.99, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 2.29, inStock: true },
      ]},
    ],
    instructions: [
      "Rinse lentils until water runs clear",
      "Sauté onion, garlic, and ginger until fragrant (about 3 minutes)",
      "Add spices (turmeric, cumin, garam masala) and toast for 30 seconds",
      "Add lentils, broth, and coconut milk",
      "Bring to a boil, then reduce heat and simmer for 20 minutes until lentils are tender",
      "Stir in spinach until wilted",
      "Season with salt to taste and serve over rice",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    nutrition: {
      calories: 320,
      protein: 14,
      carbs: 42,
      fat: 12,
      fiber: 8,
    },
    dietaryTags: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    cuisine: "Indian",
    difficulty: "easy",
    estimatedCost: 10.32,
    cheapestStore: "Trader Joe's",
    isSaved: true,
    madeCount: 2,
  },
  {
    id: "2",
    name: "Chickpea & Veggie Curry",
    description: "A hearty, budget-friendly curry loaded with vegetables and plant protein. Ready in under 30 minutes!",
    ingredients: [
      { name: "Chickpeas", amount: 2, unit: "cans", price: 1.98, cheapestStore: "Trader Joe's", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 1.98, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 3.38, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 2.58, inStock: true },
      ]},
      { name: "Cauliflower", amount: 1, unit: "head", price: 2.99, cheapestStore: "Trader Joe's" },
      { name: "Bell pepper", amount: 2, unit: "medium", price: 1.98, cheapestStore: "Safeway" },
      { name: "Coconut cream", amount: 1, unit: "can", price: 2.49, cheapestStore: "Trader Joe's" },
      { name: "Curry powder", amount: 2, unit: "tbsp", price: 0.40, cheapestStore: "Trader Joe's" },
      { name: "Tomato paste", amount: 2, unit: "tbsp", price: 0.50, cheapestStore: "Safeway" },
      { name: "Onion", amount: 1, unit: "large", price: 0.60, cheapestStore: "Safeway" },
      { name: "Garlic", amount: 4, unit: "cloves", price: 0.40, cheapestStore: "Trader Joe's" },
    ],
    instructions: [
      "Dice onion and mince garlic",
      "Sauté onion and garlic until golden (about 5 minutes)",
      "Add curry powder and tomato paste, stir well",
      "Add cauliflower florets and bell peppers",
      "Pour in coconut cream and drained chickpeas",
      "Simmer for 20 minutes until vegetables are tender",
      "Season to taste and serve with naan or rice",
    ],
    prepTime: 15,
    cookTime: 25,
    servings: 6,
    nutrition: {
      calories: 285,
      protein: 11,
      carbs: 38,
      fat: 10,
      fiber: 10,
    },
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
    cuisine: "Indian",
    difficulty: "easy",
    estimatedCost: 11.34,
    cheapestStore: "Trader Joe's",
    isSaved: false,
    madeCount: 0,
  },
  {
    id: "3",
    name: "Black Bean Tacos",
    description: "Quick, customizable, and packed with flavor. Perfect for busy weeknights when you want something satisfying.",
    ingredients: [
      { name: "Black beans", amount: 2, unit: "cans", price: 1.98, cheapestStore: "Trader Joe's", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 1.98, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 3.38, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 2.58, inStock: true },
      ]},
      { name: "Corn tortillas", amount: 12, unit: "small", price: 2.99, cheapestStore: "Trader Joe's" },
      { name: "Avocado", amount: 2, unit: "medium", price: 1.58, cheapestStore: "Trader Joe's", storeOptions: [
        { storeId: "tj", storeName: "Trader Joe's", price: 1.58, inStock: true },
        { storeId: "wf", storeName: "Whole Foods", price: 3.00, inStock: true },
        { storeId: "safeway", storeName: "Safeway", price: 2.00, inStock: true },
      ]},
      { name: "Red cabbage", amount: 2, unit: "cups", price: 1.50, cheapestStore: "Safeway" },
      { name: "Lime", amount: 2, unit: "whole", price: 0.50, cheapestStore: "Trader Joe's" },
      { name: "Cilantro", amount: 1, unit: "bunch", price: 0.99, cheapestStore: "Trader Joe's" },
      { name: "Cumin", amount: 1, unit: "tsp", price: 0.15, cheapestStore: "Trader Joe's" },
      { name: "Chipotle powder", amount: 0.5, unit: "tsp", price: 0.10, cheapestStore: "Trader Joe's" },
      { name: "Salsa verde", amount: 1, unit: "cup", price: 3.49, cheapestStore: "Trader Joe's" },
    ],
    instructions: [
      "Drain and rinse black beans",
      "Season beans with cumin and chipotle, warm in a pan",
      "Warm tortillas in a dry pan until pliable",
      "Shred cabbage thinly and chop cilantro",
      "Slice avocado and cut limes into wedges",
      "Assemble tacos with beans, cabbage, avocado, cilantro",
      "Top with salsa verde and a squeeze of lime",
    ],
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    nutrition: {
      calories: 340,
      protein: 12,
      carbs: 48,
      fat: 14,
      fiber: 14,
    },
    dietaryTags: ["vegetarian", "vegan", "dairy-free"],
    cuisine: "Mexican",
    difficulty: "easy",
    estimatedCost: 13.28,
    cheapestStore: "Trader Joe's",
    isSaved: true,
    madeCount: 1,
  },
  {
    id: "4",
    name: "Mediterranean Quinoa Bowl",
    description: "Fresh, colorful, and nutritious. A perfect meal prep option that tastes even better the next day.",
    ingredients: [
      { name: "Quinoa", amount: 1, unit: "cup", price: 3.99, cheapestStore: "Trader Joe's" },
      { name: "Cucumber", amount: 1, unit: "large", price: 0.99, cheapestStore: "Trader Joe's" },
      { name: "Cherry tomatoes", amount: 1, unit: "pint", price: 3.49, cheapestStore: "Trader Joe's" },
      { name: "Kalamata olives", amount: 0.5, unit: "cup", price: 2.99, cheapestStore: "Trader Joe's" },
      { name: "Red onion", amount: 0.5, unit: "medium", price: 0.40, cheapestStore: "Safeway" },
      { name: "Hummus", amount: 0.5, unit: "cup", price: 2.49, cheapestStore: "Trader Joe's" },
      { name: "Lemon", amount: 1, unit: "whole", price: 0.50, cheapestStore: "Trader Joe's" },
      { name: "Olive oil", amount: 2, unit: "tbsp", price: 0.50, cheapestStore: "Trader Joe's" },
    ],
    instructions: [
      "Cook quinoa according to package directions, let cool",
      "Dice cucumber and halve cherry tomatoes",
      "Thinly slice red onion",
      "Combine cooled quinoa with vegetables and olives",
      "Whisk lemon juice and olive oil for dressing",
      "Toss salad with dressing",
      "Serve with a dollop of hummus",
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    nutrition: {
      calories: 295,
      protein: 9,
      carbs: 38,
      fat: 13,
      fiber: 6,
    },
    dietaryTags: ["vegetarian", "vegan", "gluten-free"],
    cuisine: "Mediterranean",
    difficulty: "easy",
    estimatedCost: 15.35,
    cheapestStore: "Trader Joe's",
    isSaved: false,
    madeCount: 0,
  },
];

export const dummyGroceryComparison: GroceryComparison[] = [
  {
    ingredient: "Red lentils (1 lb)",
    stores: [
      { store: dummyStores[0], price: 2.99, inStock: true, isCheapest: true },
      { store: dummyStores[1], price: 4.49, inStock: true, isCheapest: false },
      { store: dummyStores[2], price: 3.79, inStock: true, isCheapest: false },
    ],
  },
  {
    ingredient: "Coconut milk (13.5 oz)",
    stores: [
      { store: dummyStores[0], price: 1.99, inStock: true, isCheapest: true },
      { store: dummyStores[1], price: 2.99, inStock: true, isCheapest: false },
      { store: dummyStores[2], price: 2.49, inStock: false, isCheapest: false },
    ],
  },
  {
    ingredient: "Fresh spinach (5 oz)",
    stores: [
      { store: dummyStores[0], price: 2.49, inStock: true, isCheapest: false },
      { store: dummyStores[1], price: 3.99, inStock: true, isCheapest: false },
      { store: dummyStores[2], price: 2.29, inStock: true, isCheapest: true },
    ],
  },
  {
    ingredient: "Chickpeas (15 oz can)",
    stores: [
      { store: dummyStores[0], price: 0.99, inStock: true, isCheapest: true },
      { store: dummyStores[1], price: 1.69, inStock: true, isCheapest: false },
      { store: dummyStores[2], price: 1.29, inStock: true, isCheapest: false },
    ],
  },
  {
    ingredient: "Avocados (each)",
    stores: [
      { store: dummyStores[0], price: 0.79, inStock: true, isCheapest: true },
      { store: dummyStores[1], price: 1.50, inStock: true, isCheapest: false },
      { store: dummyStores[2], price: 1.00, inStock: true, isCheapest: false },
    ],
  },
];

export const dummyMealPlan: MealPlan = {
  id: "mp1",
  startDate: new Date("2025-02-10"),
  endDate: new Date("2025-02-17"),
  totalCost: 73,
  groceryList: [],
  days: [
    {
      date: new Date("2025-02-10"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b1", name: "Overnight Oats with Berries", nutrition: { calories: 320, protein: 12, carbs: 45, fat: 8, fiber: 6 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[3], id: "l1", name: "Mediterranean Quinoa Bowl" } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[0], servings: 2 },
      },
      dailyNutrition: { calories: 1380, protein: 55, carbs: 181, fat: 48, fiber: 30 },
    },
    {
      date: new Date("2025-02-11"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b2", name: "Banana Peanut Butter Smoothie", nutrition: { calories: 380, protein: 14, carbs: 48, fat: 16, fiber: 5 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[0], id: "l2", name: "Leftover Lentil Dal", nutrition: { calories: 320, protein: 14, carbs: 42, fat: 12, fiber: 8 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[1], servings: 2 },
      },
      dailyNutrition: { calories: 1270, protein: 50, carbs: 166, fat: 50, fiber: 31 },
    },
    {
      date: new Date("2025-02-12"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b3", name: "Avocado Toast with Seeds", nutrition: { calories: 340, protein: 10, carbs: 32, fat: 20, fiber: 8 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[1], id: "l3", name: "Leftover Chickpea Curry", nutrition: { calories: 285, protein: 11, carbs: 38, fat: 10, fiber: 10 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[2], servings: 2 },
      },
      dailyNutrition: { calories: 1305, protein: 45, carbs: 166, fat: 58, fiber: 46 },
    },
    {
      date: new Date("2025-02-13"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b4", name: "Greek Yogurt Parfait", nutrition: { calories: 290, protein: 18, carbs: 38, fat: 8, fiber: 4 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[2], id: "l4", name: "Leftover Black Bean Tacos", nutrition: { calories: 340, protein: 12, carbs: 48, fat: 14, fiber: 14 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[3], servings: 2 },
      },
      dailyNutrition: { calories: 1220, protein: 49, carbs: 162, fat: 49, fiber: 30 },
    },
    {
      date: new Date("2025-02-14"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b5", name: "Chia Pudding", nutrition: { calories: 280, protein: 8, carbs: 32, fat: 14, fiber: 10 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[3], id: "l5", name: "Leftover Quinoa Bowl", nutrition: { calories: 295, protein: 9, carbs: 38, fat: 13, fiber: 6 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[0], servings: 2 },
      },
      dailyNutrition: { calories: 1215, protein: 45, carbs: 154, fat: 51, fiber: 32 },
    },
    {
      date: new Date("2025-02-15"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b6", name: "Veggie Scramble", nutrition: { calories: 320, protein: 16, carbs: 12, fat: 24, fiber: 4 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[0], id: "l6", name: "Leftover Lentil Dal", nutrition: { calories: 320, protein: 14, carbs: 42, fat: 12, fiber: 8 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[1], servings: 2 },
      },
      dailyNutrition: { calories: 1210, protein: 52, carbs: 130, fat: 56, fiber: 32 },
    },
    {
      date: new Date("2025-02-16"),
      meals: {
        breakfast: { recipe: { ...dummyRecipes[0], id: "b7", name: "Pancakes with Fresh Fruit", nutrition: { calories: 420, protein: 10, carbs: 68, fat: 12, fiber: 4 } } as Recipe, servings: 1 },
        lunch: { recipe: { ...dummyRecipes[1], id: "l7", name: "Leftover Chickpea Curry", nutrition: { calories: 285, protein: 11, carbs: 38, fat: 10, fiber: 10 } } as Recipe, servings: 1 },
        dinner: { recipe: dummyRecipes[2], servings: 2 },
      },
      dailyNutrition: { calories: 1385, protein: 45, carbs: 202, fat: 50, fiber: 42 },
    },
  ],
};

export const dummyChatHistory: ChatMessage[] = [
  {
    id: "1",
    role: "assistant",
    content: "Hey there! I'm Mahm, your AI nutritionist and meal planning buddy. I'm here to help you eat well without the stress. Tell me a bit about yourself - any dietary restrictions, allergies, or foods you absolutely can't stand? And what's your weekly grocery budget looking like?",
    timestamp: new Date("2025-02-10T10:00:00"),
  },
  {
    id: "2",
    role: "user",
    content: "I'm vegetarian, lactose intolerant, trying to lose weight, $80/week budget",
    timestamp: new Date("2025-02-10T10:01:00"),
  },
  {
    id: "3",
    role: "assistant",
    content: "Got it! Vegetarian + lactose-free + weight loss goals on $80/week - totally doable. A few more quick questions to make sure I nail this:\n\n1. **Cooking skill level?** (Total beginner, comfortable, or chef mode?)\n2. **Any foods you hate?** (No judgment - we all have our nemeses)\n3. **How much time do you have for cooking on weeknights?** (15 min? 30? An hour?)",
    timestamp: new Date("2025-02-10T10:02:00"),
  },
  {
    id: "4",
    role: "user",
    content: "Beginner. Hate tofu. Usually have about 30 mins on weeknights",
    timestamp: new Date("2025-02-10T10:03:00"),
  },
  {
    id: "5",
    role: "assistant",
    content: "Perfect! No tofu, beginner-friendly, 30-min max. I've got you covered.\n\nHere are 3 dinner ideas that fit your needs - all high-protein (since you mentioned weight loss), dairy-free, and totally beginner-proof:",
    timestamp: new Date("2025-02-10T10:04:00"),
    toolCalls: [
      { id: "tc1", name: "search_recipes", status: "complete" },
      { id: "tc2", name: "get_nutrition", status: "complete" },
    ],
  },
];

export const dummyUserProfile: UserProfile = {
  id: "user1",
  name: "Alex",
  email: "alex@example.com",
  preferences: {
    dietaryRestrictions: ["vegetarian"],
    allergies: ["lactose"],
    dislikedFoods: ["tofu", "mushrooms"],
    budget: 80,
    budgetPeriod: "weekly",
    cookingSkill: "beginner",
    availableTime: 30,
    healthGoals: ["weight loss", "more energy"],
    householdSize: 1,
  },
  savedRecipes: ["1", "3"],
  madeRecipes: [],
  createdAt: new Date("2025-01-01"),
  updatedAt: new Date("2025-01-15"),
};

export const dummyJournalEntries: RecipeJournalEntry[] = [
  {
    id: "j1",
    recipeId: "1",
    recipeName: "Creamy Lentil Dal",
    madeAt: new Date("2025-02-03"),
    rating: 5,
    photos: [],
    notes: "So good! Added extra spinach.",
    modifications: "Used lite coconut milk, added a pinch of cayenne",
    wouldMakeAgain: true,
  },
  {
    id: "j2",
    recipeId: "1",
    recipeName: "Creamy Lentil Dal",
    madeAt: new Date("2025-02-08"),
    rating: 5,
    photos: [],
    notes: "Even better the second time!",
    modifications: "Same as before",
    wouldMakeAgain: true,
  },
  {
    id: "j3",
    recipeId: "3",
    recipeName: "Black Bean Tacos",
    madeAt: new Date("2025-02-06"),
    rating: 4,
    photos: [],
    notes: "Quick and easy weeknight dinner",
    modifications: "Skipped the chipotle, used flour tortillas instead",
    wouldMakeAgain: true,
  },
];

export const dummyShortFormContent: ShortFormContent[] = [
  {
    id: "sf1",
    platform: "tiktok",
    url: "https://www.tiktok.com/@example/video/123",
    thumbnailUrl: "/api/placeholder/200/350",
    title: "5-minute healthy breakfast that changed my life",
    creator: "@healthyeats",
    recipeId: undefined,
  },
  {
    id: "sf2",
    platform: "instagram",
    url: "https://www.instagram.com/reel/abc123",
    thumbnailUrl: "/api/placeholder/200/350",
    title: "Budget meal prep under $50/week",
    creator: "@mealprepqueen",
    recipeId: undefined,
  },
  {
    id: "sf3",
    platform: "youtube",
    url: "https://youtube.com/shorts/xyz789",
    thumbnailUrl: "/api/placeholder/200/350",
    title: "The viral cucumber salad recipe",
    creator: "@foodtok",
    recipeId: undefined,
  },
];
